version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: nil.waddle
      POSTGRES_PASSWORD: nil2020
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgresql://nil.waddle:nil2020@db:5432/test_db"

volumes:
  postgres_data:
